### ISSUE TITLE
Simplify Command Notation

### ISSUE THREAD

**Issue by KeyboardCowboy** [KeyboardCowboy/drush-denver#24]
Current command notation is very terse.

Ex.

```yml
commands:
  command-name:
    @site.alias
    arguments:
      arg1: value
    options:
      opt1: value
      opt2:
        - item1
        - item2
```

This could be simplified by using the notation we are already familiar with to identify args, opts and aliases.

Ex. 
```yml
commands:
  command-name:
    @site.alias
    arg1: value
    arg2: value
    --opt1: value
    --opt2:
      - item1
      - item2
```
